### ISSUE TITLE
Movement: Bouncing Box and static text

### ISSUE THREAD

**Issue by tcconway** [Alteka/Kards#44]
Would like to request two movement features:

**Bouncing box**
Enabling this requested feature would overlay a bouncing box that bounces left-right and back again. This proves movement, but also keeps Bars/Test Card/Ramp/Color/Text etc in position.

**Static text**
This request is to keep the text static while the backgrounds move. The current movement makes it look like there's a sync or a locking issue. If the foreground text stays static, it's much more clear that the movement is intended.

Thanks.

**Comment by DrewLX** [comment]
I like the ideas, this comes down to treading the line between complexity and usefulness. With Kards we're aiming to make the use of the app as simple as possible. 

We avoided anything remaining static (apart from the Alteka type) in order to avoid screen burn. 

To avoid a sync/locking issue but also avoid screen burn we could make the info circle move in a different direction?

@canoemoose What do you think? We could add more animation options?

**Comment by tcconway** [comment]
Thanks for your consideration. Although I don’t think burn-in is an issue with today’s monitors anymore, what about considering repositioning the circle/text every few seconds?

**Comment by canoemoose** [comment]
It's that fine line between everything being configurable and everyday use having too many options.
I like the idea of the infocircle remaining still but the burn-in risk is definitely there - even if it's image retention rather than true burn-in these days. We've seen this on Samsung professional displays run at 100% brightness for a while.
I think I prefer the idea of it jumping every 15 seconds, rather than moving in the opposide direction.

Same with the bouncing box really. Like the idea, don't know whether it'd just end up more cluttered.

**Comment by DrewLX** [comment]
It doesn't have to move in the opposite direction. It could move in a circular motion, rotating about centre. Simple CSS animation.

**Comment by DrewLX** [comment]
I've had a quick play with UI and there are only two sensible options.

1) The motion switch is replaced with a three or four way radio group. So this could be 'Off', 'Basic', 'Minimal', 'Full' for example.

2) Replace it with a dropdown selector. This can be multiple select. So you can independently toggle the Info Circle, the card and an extra overlay object as suggested by @tcconway 

Option 2 is nice but complex for someone who just wants to turn it on and it work. Option 1 is ok but it's hard to distill it down to 3 or 4 options.

**Comment by DrewLX** [comment]
We're talking about adding an 'advanced' options modal. At which point I feel like we can offer a simple toggle switch for 'Info Circle moves with card' boolean. If off, it stays in the centre. If on, it works as current version. How does that sound?

**Comment by tcconway** [comment]
Thanks!
